#!/usr/bin/env php
<?php

$autoloadFiles = [
	__DIR__ . '/../../autoload.php',
	__DIR__ . '/../vendor/autoload.php',
	__DIR__ . '/vendor/autoload.php'
];

foreach ($autoloadFiles as $autoloadFile) {
	if (file_exists($autoloadFile)) {
		require_once $autoloadFile;
		break;
	}
}

use Pragnesh\LaravelPackageHelper\Command;
use Symfony\Component\Console\Application;

$app = new Application();

$app->addCommands([
	new Command\CreateConfigCommand,
	//new MakeTestCommand(),
	new Command\MakeControllerCommand,
	new Command\MakeModelCommand,
	new Command\MakeFactoryCommand,
	new Command\MakeMigrationCommand,
	new Command\MakeSeederCommand,
	new Command\MakePolicyCommand,
	new Command\MakeRequestCommand,
	new Command\MakeProviderCommand,
	new Command\MakeConsoleCommand,
]);

$app->run();